# Netlify deployment configuration
[build]
  publish = "."
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Redirect all requests to index.html for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200